import "./core/hash.test.ts";
import "./core/normalize.test.ts";
import "./core/invariants.test.ts";
import "./bench/regression-dataset-schema.test.ts";
import "./bench/bench-run-malformed-regression.test.ts";
import "./engine/chunk-map-span.test.ts";
import "./engine/checkpoint-retry-executor.test.ts";
import "./engine/json-pipeline-run.test.ts";
import "./engine/long-text-fixture.test.ts";
import "./engine/prompt-compiler.test.ts";
import "./engine/run-with-evidence.test.ts";
import "./evidence/attestation.test.ts";
import "./eval/run-suite.test.ts";
import "./io/jsonl.test.ts";
import "./json/extract-json.test.ts";
import "./json/repair.test.ts";
import "./json/parse.test.ts";
import "./providers/fake-e2e.test.ts";
import "./providers/real-providers.test.ts";
import "./regression/semantic-identifiers-and-placeholder-ban.test.ts";
import "./regression/multi-pass-execution-model.test.ts";
import "./regression/provider-structured-generate-split.test.ts";
import "./schema/validate.test.ts";
import "./schema/to-json-schema.test.ts";
import "./viz/html.test.ts";
import { run } from "./harness.ts";

await run();
